### ISSUE TITLE
Preserving current directory path when creating a new tab

### ISSUE THREAD

**Issue by daaugusto** [mina86/urxvt-tabbedex#13]
Hi,

I recently migrated from roxterm to urxvt+tabbedex and one thing a miss a lot is the possibility of automatically changing to the working directory of the current tab immediately after a new tab is created. Is there a configuration for that? If not, would it be difficult to implement such behavior?

Thank you.

**Comment by mina86** [comment]
There is no clean way of doing this. You might want to take a look at https://github.com/stepb/urxvt-tabbedex/issues/13 but it requires your window title to be of specific format which is why it’s not upstreamed.

If you want to play with implementing this feature, possible better approaches would be:
1. Figuring out process in foreground of the current tab and getting CWD of that process. Provided the same user runs urxvt as the process in foreground, CWD can be read from `/proc/PID/cwd` link.
2. Implementing OSC which informs tabbedex of CWD.

The first one has additional advantage that it won’t suffer from paths sent from remote hosts (e.g. when you SSH) and should work better with filesystem namespaces. It will also work regardless of how your shell is configured and with other tools like `ftp` client.

The downside is that it won’t work if you sudo.

**Comment by daaugusto** [comment]
Hi mina86, thanks for your helpful reply.

**Comment by mina86** [comment]
https://github.com/mina86/urxvt-tabbedex/tree/experimental has this feature implemented. As name suggests, it’s experimental so no guarantees on whether it actually works. There’s also no configuration of this feature as of now.

**Comment by mina86** [comment]
This is now implemented (with caveats around accuracy of directory detection). See `command-runner.sample` file in master branch for documentation what can be done with the new `tab-arguments` resource.
