### ISSUE TITLE
Bug in rxvt-unicode when resizing window. A part of content just dissapears after resizing window.

### ISSUE THREAD

**Issue by ProgrammingLife** [mina86/urxvt-tabbedex#34]
Steps to reproduce: When you have some text in rxvt then you just resize the window smaller (vertically) and then back to its previous state. I'm doing it using my mouse. In my case a part of content inside rxvt dissapears. 

If I turning off tabbedex then the bug goes away and vice versa.

**Env:**
Linux Mint: **19.1**
rxvt-unicode: **(urxvt) v9.22 - released: 2016-01-23**

**Comment by mina86** [comment]
I can reproduce it however this is an upstream behaviour and it does not relate to tabbedex.

The problem is that urxvt reflows text only if scroll-back is available. In other words, if after opening the terminal I run `echo $(seq $COLUMNS)` and then resize window horizontally, the text will indeed disappear. However, if I run `seq $LINES; echo $(seq $COLUMNS)`, the text will reflow when resizing the window. This behaviour is the same regardless of whether tabbedex is enabled or not.

There is a [bug report|https://rxvt-unicode.schmorp.narkive.com/KXRJ72iG/resize-eats-output] about vertical resizing but I believe the root cause is the same.

**Comment by ProgrammingLife** [comment]
@mina86, thanks for reserching it. I got it.
