### ISSUE TITLE
Changing directory of a new tab doesn't work

### ISSUE THREAD

**Issue by ProgrammingLife** [mina86/urxvt-tabbedex#41]
I've tried a few commands for changing a directory of opened tab but they are all failed:
```
URxvt.keysym.F1:	tabbedex:new_tab_after_this:-e cd ~/.config
URxvt.keysym.F2:	tabbedex:new_tab_after_this:-e /bin/bash %"cd ~/.config"
URxvt.keysym.F3:	tabbedex:new_tab_after_this:-e /bin/bash %"sleep 2; cd ~/.config"
```
What's wrong with this approach?
I've noticed about "command-runner.sample" but I want to why why does this approach not work?

**Comment by mina86** [comment]
`cd` is a built which affects the state of current shell so it cannot be executed as tried in `F1` example.

For the other two, the commands themselves are almost right but you don’t need the percentage sign and need `-c` option to bash (i.e. `-e /bin/bash -c "cd ~/.config"`). However, this time the issue is that this will start bash which will execute `cd ~/.config` and as soon as that’s done it’ll exit. Instead you need to execute bash after changing the directory as in:

    URxvt.keysym.F2: tabbedex:new_tab_after_this:-e /bin/sh -c "cd ~/.config && exec /bin/bash"

**Comment by ProgrammingLife** [comment]
@mina86 Wow, thanks a ton!
Do you happen to know how to exec cd to the last directory which was opened in the previous tab? I wanna open new tab in the same directory

**Comment by mina86** [comment]
You can use `pgid-cd.pl` for that. It has example in documentation.
