### ISSUE TITLE
launching two tabs with command running?

### ISSUE THREAD

**Issue by rudevdr** [mina86/urxvt-tabbedex#43]
I've been looking around to learn how to create a script which launches two new tabs in the same urxvt window and launches some script or executes a command in the tab. if script is launched without urxvt then it launches a new urxvt window and then performs the job (launching 2 tab and launching script there). 

I've tried looking into the code but I"m not familiar with perl so can't figure out much how perl scripts for urxvt are launched with cli. Is [mina86/urxvt-tabbedex/command-runner.sample](https://github.com/mina86/urxvt-tabbedex/blob/master/command-runner.sample) made for this?

How are urxvt perl extensions like this are imported to use with bash or python?

**Comment by mina86** [comment]
You can use command-runner to run different commands in each tab. The sample file will run bash in first tab, Emacs in second, tail log in third and then whatever is the default urxvt command in remaining tabs.

There is however no way to start urxvt with two tabs open. It’s a non-trivial problem because of security implications. It wouldn’t be desired if application running in a terminal could spam the terminal and make it open hundreds of tabs.

You can hack your copy of `tabbedex` by editing `_on start` section and adding another call to `$root->new_tab;` if you really need that feature.

**Comment by rudevdr** [comment]
> There is however no way to start urxvt with two tabs open. It’s a non-trivial problem because of security implications. It wouldn’t be desired if application running in a terminal could spam the terminal and make it open hundreds of tabs.

Okay that explain things. Thanks :)

I got it working now :+1: 

Btw there seems typo here https://github.com/mina86/urxvt-tabbedex/blob/master/command-runner.sample#L57, I believe you meant `tabbedex-pgid-cd` not `tabbadex-pgid-cd`
